name: arquitectura
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn
  - pandas
  - numpy<2.0.0
  - pytest
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - plotly
  - ipyleaflet
  - pylint
  - autopep8
  - joblib
  - lxml
  - boto3
  - awswrangler
  - xgboost
  - streamlit
  - altair
  - sphinx
  - sphinxcontrib-napoleon
  - myst-parser
  - pip
  - pip:
    - sphinxawesome_theme