# Dockerfile para entrenamiento
FROM python:3.11-slim

WORKDIR /app

# Copiar archivos necesarios
COPY src/inference.py .
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Definir argumentos y comando de inicio
ENTRYPOINT ["python", "inference.py"]
# Argumentos para definir rutas de datos y modelo:
CMD ["--input", "data/inference/test.csv", "--output", "data/predictions/predictions.csv", "--model", "model/model.joblib"]